### ISSUE TITLE
PNG logo is looking blurry. Can we use SVG?

### ISSUE THREAD

**Issue by anexasajoop** [twozeroone/tikola#10]

**Comment by prtksxna** [comment]
For security reasons a default Wordpress install doesn't allow one to upload SVGs. Will have to see what config needs to change to fix this.

**Comment by anexasajoop** [comment]
Ok. Any idea why the PNG is looking blurry?

**Comment by prtksxna** [comment]
I was scaling it down to `500px`, I have removed that constraint now. Is it better?

**Comment by anexasajoop** [comment]
Not really ):

**Comment by anexasajoop** [comment]
From @prtksxna, if image needs changing:

http://isl.prtksxna.com/wp-admin/customize.php?url=http%3A%2F%2Fisl.prtksxna.com%2F
Go to Site Identity, and click "Change logo"
