### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by anexasajoop** [twozeroone/tikola#15]
Footer can have solid grey background and the following text —

India Street Lettering documents street lettering and signage in India, across scripts and styles. Much of it is changing constantly, and vernacular signs are quickly disappearing.  

Run by Pooja Saxena. Find her on Instagram and Twitter.

Made by Prateek Saxena, Amber Sinha and Pooja Saxena.

**Comment by prtksxna** [comment]
You can edit content here http://isl.prtksxna.com/wp-admin/widgets.php

**Comment by anexasajoop** [comment]
Thank you (:

**Comment by anexasajoop** [comment]
The footer is not sticking to the bottom of the page right now if the content on the page is less.

**Comment by anexasajoop** [comment]
@prtksxna ^
