### ISSUE TITLE
Choose map tiles

### ISSUE THREAD

**Issue by anexasajoop** [twozeroone/tikola#16]

**Comment by prtksxna** [comment]
You can see the default tiles at https://www.mapbox.com/maps/#styles under the "Choose a map" heading.

**Comment by anexasajoop** [comment]
Mapbox Light

**Comment by prtksxna** [comment]
If you're admin you can change it from http://isl.prtksxna.com/wp-admin/options-media.php
I've updated the map page too! Sorry that it does not use that setting. The setting is for the plugin, and the map is being created by our theme :/
